# Generated by Django 6.1 on 2026-09-27 11:24

import uuid
from django.db import migrations, models

# The six initial hospital departments (product-defined).
INITIAL_DEPARTMENTS = [
    "Pediatrics",
    "Surgery",
    "Internal Medicine",
    "Obstetrics & Gynaecology",
    "Mental Health & Psychiatry",
    "General",
]


def seed_departments(apps, schema_editor):
    """Create the six initial departments if they do not exist."""
    Department = apps.get_model("departments", "Department")
    for name in INITIAL_DEPARTMENTS:
        Department.objects.get_or_create(name=name)


def remove_seeded_departments(apps, schema_editor):
    """Reverse migration: remove the seeded departments.

    Runs after the encounters FK column is dropped (reverse dependency
    order), so no protected references remain.
    """
    Department = apps.get_model("departments", "Department")
    Department.objects.filter(name__in=INITIAL_DEPARTMENTS).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'departments_department',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(
            seed_departments,
            remove_seeded_departments,
        ),
    ]
